apiVersion: v2
name: kindCluster
description: Helm chart for Kind Cluster components
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kind
  - cluster
  - kubernetes
maintainers:
  - name: CodeInspector Team
