{{- if .Values.storage.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName | default "scan-pvc" }}
  namespace: {{ .Values.namespace | default "opensandbox-system" }}
  labels:
    app: opensandbox-server
    component: scan-pvc
spec:
  accessModes:
    - {{ .Values.storage.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "10Gi" }}
{{- end }}
