apiVersion: v1
kind: Secret
metadata:
  name: sandbox-api-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  E2B_API_KEY: {{ .Values.secret.E2B_API_KEY | b64enc | quote }}
  JWT_PRIVATE_KEY: {{ .Values.secret.JWT_PRIVATE_KEY | b64enc | quote }}
