apiVersion: v1
kind: Service
metadata:
  name: sandbox-api-service
  namespace: {{ .Values.namespace }}
  labels:
    app: sandbox-api
spec:
  selector:
    app: sandbox-api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
