# Default values for agentgateway
namespace: agentgateway-system

httproute:
  hostnames:
    - dipper-shun-glowing.ngrok-free.dev
  backendService:
    name: sandbox-api-service
    port: 80

gateway:
  gatewayClassName: agentgateway
  listeners:
    - protocol: HTTP
      port: 80
      name: http

policy:
  authenticationType: "jwt"

secret:
  signingKey: "default-signing-secret-change-me"
