apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: agentgateway-proxy
  namespace: {{ .Values.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  {{- range .Values.gateway.listeners }}
  - protocol: {{ .protocol }}
    port: {{ .port }}
    name: {{ .name }}
    allowedRoutes:
      namespaces:
        from: All
  {{- end }}
