{{- if not (eq .Values.policy.authenticationType "none") }}
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: apikey-auth
  namespace: {{ .Values.namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: agentgateway-api-route
  traffic:
    rateLimit:
      local:
        tokenBucket:
          maxTokens: 7
          tokensPerFill: 5
          fillInterval: 60s
{{- end }}
