{{- if not (eq .Values.policy.authenticationType "none") }}
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: apikey-auth
  namespace: {{ .Values.namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: agentgateway-api-route
  traffic: 
    {{- if eq .Values.policy.authenticationType "apiKey" }}
    apiKeyAuthentication:
      mode: {{ .Values.policy.apiKeyAuthentication.mode | default "Strict" }}
      secretRef:
        name: apikey
    {{- else }}
    {}
    {{- end }}
{{- end }}
