apiVersion: v1
kind: Secret
metadata:
  {{- if eq .Values.policy.authenticationType "jwt" }}
  name: jwt-signing-key
  {{- else }}
  name: apikey
  {{- end }}
  namespace: {{ .Values.namespace }}
  labels:
    app: httpbin
{{- if eq .Values.policy.authenticationType "jwt" }}
type: Opaque
{{- else }}
type: extauth.solo.io/apikey
{{- end }}
stringData:
  {{- if eq .Values.policy.authenticationType "jwt" }}
  signing-key: {{ .Values.secret.signingKey }}
  {{- else }}
  api-key: {{ .Values.secret.apiKey }}
  {{- end }}
