apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: apikey-auth
  namespace: agentgateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: agentgateway-route
  traffic:
    jwtAuthentication:
      providers:
        - issuer: "code-inspector"
          audiences:
            - "code-inspector-api"
          jwks:
            inline: '{"keys": [{"kty": "RSA", "use": "sig", "kid": "code-inspector-key-01", "alg": "RS256", "n": "7eXFpr2rANKszQYSKd-bDRy1-M0tsatbwpr0BGkMOsZMHRph3bv9kLB0TuyLJ09VXDdmUpiYLGd6oQr3iKhtk3oe1_-p6aS7JKTZ-YCQW7TPRQget7lxWZj9l9a-E1WM-JSBjc7tXsGsKjVS9eDC-18gKbS4SnZhxhYwf08flLYa1nHhxuaUbxe7YNzqB6VMIAzt4iyC0LS3cm_CCI8hNg5RjbFkZXE_IC0rdRScLotfWOX2rgSdEH83hA41C8Nx0WICnQ6HysrBIxTfiUiQD4ieKb6HlK4Tr25hUhW_rcshhvcGyBAzQKYtadd51kADr4a0G09U95zby4pCasN-0w", "e": "AQAB"}]}'