apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: apikey-auth
  namespace: agentgateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: agentgateway-api-route
  traffic:
    jwtAuthentication:
      mode: "Permissive"
      forwardOriginalToken: true
      providers:
        - issuer: "code-inspector"
          audiences:
            - "code-inspector-api"
          jwks:
            inline: '{"keys": [{"kty": "RSA", "use": "sig", "kid": "code-inspector-key-01", "alg": "RS256", "n": "7eXFpr2rANKszQYSKd-bDRy1-M0tsatbwpr0BGkMOsZMHRph3bv9kLB0TuyLJ09VXDdmUpiYLGd6oQr3iKhtk3oe1_-p6aS7JKTZ-YCQW7TPRQget7lxWZj9l9a-E1WM-JSBjc7tXsGsKjVS9eDC-18gKbS4SnZhxhYwf08flLYa1nHhxuaUbxe7YNzqB6VMIAzt4iyC0LS3cm_CCI8hNg5RjbFkZXE_IC0rdRScLotfWOX2rgSdEH83hA41C8Nx0WICnQ6HysrBIxTfiUiQD4ieKb6HlK4Tr25hUhW_rcshhvcGyBAzQKYtadd51kADr4a0G09U95zby4pCasN-0w", "e": "AQAB"}]}'
        - issuer: "https://dev-axwc0ui527kw0c5d.us.auth0.com/"
          audiences:
            - "https://code-inspector-api"
          jwks:
            inline: '{"keys":[{"alg":"RS256","kty":"RSA","use":"sig","n":"u3KdUumTlNhdys7_bBPMq4BTEtkdQuS8_VPrE9IytsSgR7kZ1pMmtEQ_CxznF87nj0DvnCvZgBWN5Vi15BPW4Vaf-jcH1ndOjTDElTAtXAHkB8SEsSFYZAKyUQDKDRdoBHXuUpxB6p0zIEpztgkQpJnnMbhtuPa7NQitSCWjyLzpaaEQVTt-bBw860ZvRAEBqLs2nf4Aeacj8VwM8HW5jl10mLx46CgLHIsWsmBj0WFDnQstTNr76VelEVQl7-l18nZCi-KMDFdJBSCJvqSrWEWJzIgGn-L8vYBn-CCel9vJVidRzAlZK59AUCUrLlBdEYMnz86z9dzVfOQKW4eM5w","e":"AQAB","kid":"axC0qAwREjLm_QvUFSxjv"},{"alg":"RS256","kty":"RSA","use":"sig","n":"mYxlrA1TJpmkav3uFe27SgJdKNuZnX34dDSdb2u8-H4JenrwNoONnw4sxWLHOCZv1JHrCgfPLz-iLxffTE6iLWib3A5YeBES7iAAFq1KfH_JrAU50uurBYwaiMnZlINYoAGlVBWME1sdoUD3v3bULZx-OulF8omUb07_VSHvwak8Z9meRMGvtirTFT3uANu-Ix9caAD7PMR30K1YhXvbSJmgP_JphqYGNAsKWNHBfUSLo9aRguKTnM80Nswt48pR4me0S2UZaZvGN8NCELFEmS6t5LjTBfbOL7rwgH9-TQmni-lQPGjZ_s3gGkOqaMTVVEaKeKuZQ-1AntRjMoA0sQ","e":"AQAB","kid":"V-4gNYJwfsnwsUIwdnmT0"}]}'
    transformation:
      request:
        set:
          - name: "Authorization"
            value: >-
              has(request.headers['authorization']) ? request.headers['authorization'] : (has(request.headers['cookie']) && request.headers['cookie'].contains("inspector_auth=") ? "Bearer " + request.headers['cookie'].split("inspector_auth=")[1].split(";")[0] : "")
