namespace: opensandbox-system

controller:
  replicaCount: 1
  image:
    repository: opensandbox/controller
    tag: v1.0.0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  sandboxImage: "kamalberrybytes/codeinterpreter:1.0.0"

# Storage configuration for Scan Jobs
storage:
  enabled: true
  pvcName: "scan-pvc"
  size: "10Gi"
  accessMode: "ReadWriteOnce"
  mountPath: "/data"

server:
  replicaCount: 1
  image:
    repository: opensandbox/server
    tag: v1.0.0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  sandboxImage: "kamalberrybytes/codeinterpreter:1.0.0"